[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems <jo3mccain@icloud.com>"]
description = "A decentralized social network designed for a simple, cost-effective end-user platform"
edition = "2021"
license = "MIT"
name = "reaction"
repository = "https://github.com/scattered-systems/reaction.git"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
bench = false
name = "reaction"
path = "src/main.rs"
test = false

[dependencies]
