[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = []
description = "Reaction is a full-stack decentralized community center enabling users to reap the benefits of owning their information"
edition = "2021"
homepage = "https://github.com/scattered-systems/reaction"
keywords = []
name = "reaction"
readme = "README.md"
repository = "https://github.com/scattered-systems/reaction"
version = "0.1.0"

[[bin]]
bench = false
name = "reaction"

[dependencies]

[dev-dependencies]

[build-dependencies]

