version: "4.0"
services:
  application:
    build:
      context: ../fluidity
      dockerfile: Dockerfile
      target: latest
    container_name: flow
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /config:/config
      - /data:/data

  cache:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    restart: always

  ipfs-cluster-master:
    container_name:   ipfs-cluster-master
    image: ipfs/ipfs-cluster
    depends_on:
      - ipfs-peer-master
    environment:
      CLUSTER_PEERNAME: cluster
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
      CLUSTER_MONITORPINGINTERVAL: 2s
    ports:
      - "9094:9094"
      - "9096:9096"
    volumes:
      - /data/cluster/master:/data/ipfs-cluster

  ipfs-peer-master:
    container_name: ipfs-peer-master
    image: ipfs/go-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - /data/ipfs/master:/data/ipfs

volumes:
  data: