name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_PACKAGE: reaction
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test --package $CARGO_PACKAGE --verbose
      - name: Build and Push
        run: cargo publish --package $CARGO_PACKAGE --verbose