name: Rust

on:
  push:
    tags: ["v*.*.*"]
  schedule:
    - cron: '30 9 * * 5'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: cargo login ${CARGO_REGISTRY_TOKEN}
    - name: Build
      run: cargo build --verbose --release --workspace
    - name: Cache
      uses: actions/cache@v3.0.11
      with:
        path: "/target/release"
        key: "build"
    - name: Test
      run: cargo test --all --all-features --color ${CARGO_TERM_COLOR} --verbose

